### ISSUE TITLE
iZONEV2

### ISSUE THREAD

**Issue by AnthK1973** [Swamp-Ig/pizone#18]
Hi there.
First of all I wanted to say thanks so much for the detail you have here - I have recently had an iZone system installed at home.
I don't have HA - rather am running Fibaro HC3. I also have a Pi running node red where I am using IP/SystemSettings and IP/Zones1_4 HTTP requests.

So my issue is more of a query. 
I noticed you mention iZoneV2 and my system indicates iZoneV2 under local service discovery on the general settings tab.
Do you know if there is and endpoint that can be used to obtain the data you highlighted (i,e. damper positions etc)? It seems as though there may be additional data available but can't seem to access it.

Anyway thanks again - greatly appreciated

Anthony

**Comment by Swamp-Ig** [comment]
Hi, It's been a while since I looked at it. 

Not at the moment there's no data extracted from the JSON in the API as here, but in the API documentation api_docs/iZone_JSON_datastrings.h it is listed. 

From memory I think you'll need to do a V2 request for the data you're looking for, the IP/Zones1_4 doesn't list it.

**Comment by AnthK1973** [comment]
Hey thanks so much for the quick feedback - really appreciated. I'll let you know of any additional info should I get any.
